name: "Terraform Workflow"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  pull_request:
    types:
      - opened        # Trigger when a pull request is opened
      - synchronize   # Trigger when new commits are pushed to an open pull request
      - reopened      # Trigger when a previously closed pull request is reopened
    branches:
      - main
      

jobs:
  # Job 1: Terraform Formatting Check
  terraform-check:
    name: "Terraform Format Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive 

  # Job 2: Terraform Plan
  terraform-plan:
    name: "Terraform Plan"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: terraform-check # This job will only run if terraform-check succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::295056148707:role/GithubActionsRole
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  # Job 3: Terraform Apply (Only after merge to main)
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: terraform-plan # This job will only run if terraform-plan succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
